# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# test:
#   <<: *default
#   database: db/test.sqlite3

# development:
#   <<: *default
#   database: db/development.sqlite3

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000


test:
  <<: *default
  encoding: unicode
  database: fe_test

development:
  <<: *default
  encoding: unicode
  database: fe_development

production:
  url: <%= ENV["DATABASE_URL"] %>